/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'acer-pc' at '17-7-8 下午3:12' with Gradle 3.2.1
 *
 * @author acer-pc, @date 17-7-8 下午3:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
